server:
  port: 9999

file:
  upload:
    path: http://localhost:9999/
  download:
    base:
      url: http://localhost:9999/
  max:
    size: 10485760  # 10MB

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql365
    url: jdbc:mysql://localhost:3306/finance_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


#配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mt365.sbootfds.entity//
